"""Per-session capability token authentication for the Blender bridge.

Replaces the prototype's fixed port-only trust model. A per-session random
capability token is generated by the connector on bridge start and must be
passed in every bridge request. A local port is not an authorization
boundary by itself.
"""
from __future__ import annotations

import hashlib
import hmac
import os
import time
from dataclasses import dataclass
from typing import Optional


# Default token lifetime: 8 hours
DEFAULT_TOKEN_LIFETIME_SECONDS = 8 * 60 * 60


class TokenExpiredError(Exception):
    """Raised when a session token has expired."""
    pass


class TokenInvalidError(Exception):
    """Raised when a session token is absent or does not match."""
    pass


@dataclass
class SessionToken:
    """A per-session capability token with expiry."""
    token: str
    created_at: float
    expires_at: float
    session_id: str = ""

    def is_expired(self) -> bool:
        return time.time() > self.expires_at


def generate_session_token(
    lifetime_seconds: int = DEFAULT_TOKEN_LIFETIME_SECONDS,
    session_id: str = "",
) -> SessionToken:
    """Generates a cryptographically random per-session capability token."""
    raw = os.urandom(32)
    token_str = hashlib.sha256(raw).hexdigest()
    now = time.time()
    return SessionToken(
        token=token_str,
        created_at=now,
        expires_at=now + lifetime_seconds,
        session_id=session_id,
    )


def validate_token(
    provided_token: Optional[str],
    expected: SessionToken,
) -> bool:
    """Validates a provided token against the expected session token.

    Raises:
        TokenInvalidError: if the token is absent or does not match.
        TokenExpiredError: if the token has expired.

    Returns:
        True if valid.
    """
    if not provided_token:
        raise TokenInvalidError("Session token is required but was not provided.")

    if not hmac.compare_digest(str(provided_token), str(expected.token)):
        raise TokenInvalidError("Session token does not match the active session.")

    if expected.is_expired():
        raise TokenExpiredError(
            "Session token has expired. Restart the Strata bridge to generate a new token."
        )

    return True
